name: test-cypress-ci
on:
  pull_request_review:
    types: [submitted]
    branches:
  workflow_dispatch:

jobs:
 cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Install npm dependencies
        run: npm install
        
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run test
        env:
          CYPRESS_login_username: ${{secrets.CYPRESS_USERNAME}}
          CYPRESS_login_password: ${{secrets.CYPRESS_PASSWORD}}  
     
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-screenshots
          path: ./cypress/screenshots     
      
      - name: Publish Test Summary Results
        run: npx github-actions-ctrf ctrf/ctrf-report.json     
  