name: test-cypress-ci
on:
  pull_request_review:
    types: [submitted]
    branches:
  workflow_dispatch:

jobs:
 cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Set up Node.js 18.20.4
        uses: actions/setup-node@v3
        with:
          node-version: '18.20.4'

      - name: Install npm dependencies
        run: npm install
      
      - name: Copy base JSON file and update login credentials
        run: |
          # Copia el archivo base a un nuevo archivo
          cp nr_data.json nr_data_temp.json
          
          # Usa sed para reemplazar el contenido del campo "login" en nr_data_temp.json
          sed -i 's/"username": ".*"/"username": "${{ secrets.CYPRESS_USERNAME }}"/' nr_data_temp.json
          sed -i 's/"password": ".*"/"password": "${{ secrets.CYPRESS_PASSWORD }}"/' nr_data_temp.json  
        
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
         command: npx cypress run
         browser: chrome
        env:
          CYPRESS_nr_data_path: ./nr_data_temp.json
     
      - uses: actions/upload-artifact@v4.4.0
        if: always()
        with:
          name: cypress-screenshots
          path: ./cypress/screenshots     
      
      - name: Publish Test Summary Results
        if: always()
        run: npx mochawesome-merge ./cypress/reports/*.json > ./cypress/reports/merged-report.json   
  